### ISSUE TITLE
Refaktorisanje koda

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG158-my-cube-runner#3]
- [x] podela main.c na vise fajlova i njihovo povezivanje 
- [x] izbacivanje dupliciranog koda (npr. boja se postavlja sa switch(boja){case(0):Blue;break;...} i ovaj isti blok koda se moze naci na otprilike 30 mesta u vasem projektu, to je dobar znak da treba napraviti funkciju. Isto vazi za jos neke delove koda. 
- [x] Popraviti indentaciju koda (verovatno je zbrka sa mesanjem tabova i space-ova).

**Comment by janjen6** [comment]
Izvrsena podela maina, dodata biblioteka drawing.h, sredjen kod, izbacen duplicirani kod.
